[project]
name = "pdf-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "addict>=2.4.0",
    "easydict>=1.13",
    "einops>=0.8.1",
    "jupyter>=1.1.1",
    "markdown-pdf>=1.10",
    "markdown2>=2.5.4",
    "matplotlib>=3.10.8",
    "ollama>=0.6.1",
    "openai>=2.15.0",
    "pdf2image>=1.17.0",
    "pypdf>=6.6.0",
    "reportlab>=4.4.9",
    "spire-presentation>=11.1.0",
    "streamlit>=1.53.0",
]
